### ISSUE TITLE
Failed to build on Ubuntu 14.04 amd64

### ISSUE THREAD

**Issue by weakish** [mgumz/csgp#1]
## cmake

``` sh
mkdir build && cd build && cmake .. 

cmake: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

`libbz2-dev` is `1.0.6-5`.
`clang` is `3.4-1ubuntu3 (based on LLVM 3.4)`.
## gcc

``` sh
gcc -Os -o csgp main.c md5.c base64.c platform_unix.c djb/*.c

/tmp/ccvKJmH4.o: In function `get_opts':
main.c:(.text+0x9f): undefined reference to `osexit'
main.c:(.text+0x105): undefined reference to `osexit'
main.c:(.text+0x12b): undefined reference to `osexit'
main.c:(.text+0x16a): undefined reference to `osexit'
/tmp/ccvKJmH4.o: In function `read_pw':
main.c:(.text+0x219): undefined reference to `osexit'
/tmp/ccvKJmH4.o:main.c:(.text+0x24d): more undefined references to `osexit' follow
collect2: error: ld returned 1 exit status
```

gcc is `Ubuntu 4.8.2-19ubuntu1`.
## dietlibc

The same as gcc.

dietlibc is `0.33~cvs20120325-4`.

**Comment by weakish** [comment]
`undefined reference to 'osexit'` exists in current HEAD 6b7d530
gcc compiles O.K. on f65923f

cmake still has problem on f65923f though.

**Comment by mgumz** [comment]
```
$> gcc -Os -o csgp main.c md5.c base64.c platform_unix.c djb/*.c 
```

that line from README.md is missing the "platform.c" file. that should solve that issue. so, 

```
$>  gcc -Os -o csgp main.c md5.c base64.c platform.c platform_unix.c djb/*.c
```

should work.

the cmake-problem i can not reproduce. i am using 2.8.11.1 on a debian. the cmake-issue looks like a runtime problem to me (as in "running cmake in general"), csgp only depends on libc.

**Comment by weakish** [comment]
Thanks. `gcc` works. README need to update.

**Comment by mgumz** [comment]
76684791d74a84e7c4a738069a0995f7db066cc5 fixes the issue
